public with sharing class WelcomeToPwC {
    public static void printWelcomeMessage(){
        System.debug('Welcome to PwC');
        assert.isNotNull('hello');
    }
    public static void printAzureDevopsMessage(){
        System.debug('Welcome to Azure devops');
        assert.isNotNull('hello');
    }
    public static void printAzureDevopsMessage12(){
        System.debug('Hello, how r u ?');
        assert.isNotNull('hello');
    }
    public static void printAzureDevopsMessage14(){
        System.debug('Hello, how r u 14?');
        assert.isNotNull('hello');
    }
    public static void printAzureDevopsMessage15(){
        System.debug('Hello, how r u 15?');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
        assert.isNotNull('hello');
    }
}